#!/bin/bash

while getopts ":m:" opt; do
  case ${opt} in
    m )
      commit_message="$OPTARG"
      ;;
    \? )
      echo "Usage: $0 -m <commit_message>"
      exit 1
      ;;
    : )
      echo "Option -$OPTARG requires an argument."
      exit 1
      ;;
  esac
done

if [ -z "$commit_message" ]; then
  echo "Error: Commit message is required. Use -m <commit_message>"
  exit 1
fi

git add .
git commit -m "$commit_message"
git push
